import { type NextRequest, NextResponse } from "next/server"

export async function POST(request: NextRequest) {
  try {
    const { employeeData, reportType, customMessage } = await request.json()

    // Mock AI-generated report for static deployment
    const mockReport = `
# ${reportType} Performance Report

## Performance Summary
The employee has completed ${employeeData.callsCompleted || "multiple"} calls with a success rate of ${employeeData.successRate || "85"}%. This performance demonstrates ${employeeData.trend || "consistent"} improvement in their Video KYC handling capabilities.

## Key Achievements
• Successfully maintained a ${employeeData.successRate || "85"}% success rate across all calls
• Average call duration of ${employeeData.avgDuration || "4m 30s"} shows efficient processing
• Demonstrated strong customer service skills during verification sessions

## Areas for Improvement
${employeeData.commonErrors?.length ? 
  `• Address common issues: ${employeeData.commonErrors.join(", ")}` : 
  "• Continue monitoring for process optimization opportunities"
}
• Focus on reducing error rate from ${employeeData.errorRate || "15"}% to under 10%
• Implement proactive customer communication strategies

## Specific Action Items
1. Review error patterns and implement corrective measures
2. Attend additional training on document verification best practices
3. Practice clear communication techniques for customer guidance
4. Set target to improve success rate to 90%+ in next review period

## Encouragement & Next Steps
Your dedication to quality verification processes is commendable. Continue focusing on accuracy and customer service excellence. The consistent performance trend shows strong potential for continued growth.

${customMessage ? `\n**Additional Notes:** ${customMessage}` : ""}

---
*Report generated by AI Analytics System on ${new Date().toLocaleDateString()}*
    `.trim()

    return NextResponse.json({ report: mockReport })
  } catch (error) {
    console.error("Error generating report:", error)
    return NextResponse.json({ error: "Failed to generate report" }, { status: 500 })
  }
}
