export const flagList = [
  {
    id: "FLAG_001",
    agentId: "AGT_001",
    agentName: "Rajesh Kumar",
    flagType: "break_duration",
    severity: "high",
    status: "active",
    description: "Extended break duration detected: 45 minutes in last 2 hours during peak time",
    detectedAt: "2024-01-15T15:30:00Z",
    confidence: 92,
    evidence: {
      totalBreakTime: 45,
      expectedBreakTime: 20,
      breakFrequency: 3,
      timePattern: "Frequent breaks during peak hours (2-4 PM)",
      callsLost: 8,
      impactScore: 85,
    },
    escalated: false,
    autoGenerated: true,
  },
  // ...other flags
]; 